language: node_js

node_js:
 - "stable"

branches:
 only:
  - master

before_script:
 - npm install -g firebase-tools

after_success:
 - firebase deploy --token $FIREBASE_API_TOKEN --project foodfest-d0543
