language: node_js
node_js:
	- "7"
script:
	- echo "Deploy!!"
install:
	- npm install -g firebase-tools
after_success:
	- firebase deploy -project foodfest-d0543 -token 1/9wuMZXlx8ypx7DLKSAgJc76xIR2_QjaFCzaamaioqpc